{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.5"
    }
  },
  "component" : {
    "group" : "com.github.hvdung90",
    "module" : "vulcan-appcheck",
    "version" : "1.5",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.8.0"
      }
    } ],
    "files" : [ {
      "name" : "vulcan-appcheck-1.5.aar",
      "url" : "vulcan-appcheck-1.5.aar",
      "size" : 56924,
      "sha512" : "b23257496694e5487e0d89e549ecfd35a02dec828dfcd0dae75bca3e8b9032f119b47b6308f89b5cf42635be4cd34530a2659bf81673e2f07f028409c32d9cf1",
      "sha256" : "0bf728a50355089a8893e1f9cf6546e656c44bf910e23398090a2159d31569be",
      "sha1" : "6810cc02d097ebc5b0233dbd8de2881132809671",
      "md5" : "3cf95551903d7687e86bada3e566ed6d"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.google.firebase",
      "module" : "firebase-bom",
      "version" : {
        "requires" : "32.0.0"
      },
      "attributes" : {
        "org.gradle.category" : "platform"
      },
      "endorseStrictVersions" : true
    }, {
      "group" : "com.google.firebase",
      "module" : "firebase-appcheck-playintegrity"
    }, {
      "group" : "com.google.firebase",
      "module" : "firebase-appcheck-debug"
    }, {
      "group" : "com.google.firebase",
      "module" : "firebase-appcheck-ktx"
    }, {
      "group" : "com.google.firebase",
      "module" : "firebase-crashlytics-ktx"
    }, {
      "group" : "com.google.code.gson",
      "module" : "gson",
      "version" : {
        "requires" : "2.10"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.8.0"
      }
    } ],
    "files" : [ {
      "name" : "vulcan-appcheck-1.5.aar",
      "url" : "vulcan-appcheck-1.5.aar",
      "size" : 56924,
      "sha512" : "b23257496694e5487e0d89e549ecfd35a02dec828dfcd0dae75bca3e8b9032f119b47b6308f89b5cf42635be4cd34530a2659bf81673e2f07f028409c32d9cf1",
      "sha256" : "0bf728a50355089a8893e1f9cf6546e656c44bf910e23398090a2159d31569be",
      "sha1" : "6810cc02d097ebc5b0233dbd8de2881132809671",
      "md5" : "3cf95551903d7687e86bada3e566ed6d"
    } ]
  } ]
}